// tslint:disable
/**
 * Conduit API
 * Conduit API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Profile } from './'

/**
 * @export
 * @interface Article
 */
export interface Article {
  /**
   * @type {string}
   * @memberof Article
   */
  slug: string
  /**
   * @type {string}
   * @memberof Article
   */
  title: string
  /**
   * @type {string}
   * @memberof Article
   */
  description: string
  /**
   * @type {string}
   * @memberof Article
   */
  body: string
  /**
   * @type {Array<string>}
   * @memberof Article
   */
  tagList: Array<string>
  /**
   * @type {string}
   * @memberof Article
   */
  createdAt: string
  /**
   * @type {string}
   * @memberof Article
   */
  updatedAt: string
  /**
   * @type {boolean}
   * @memberof Article
   */
  favorited: boolean
  /**
   * @type {number}
   * @memberof Article
   */
  favoritesCount: number
  /**
   * @type {Profile}
   * @memberof Article
   */
  author: Profile
}
