// tslint:disable
/**
 * Conduit API
 * Conduit API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Comment } from './'

/**
 * @export
 * @interface MultipleCommentsResponse
 */
export interface MultipleCommentsResponse {
  /**
   * @type {Array<Comment>}
   * @memberof MultipleCommentsResponse
   */
  comments: Array<Comment>
}
