// tslint:disable
/**
 * Conduit API
 * Conduit API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Article } from './'

/**
 * @export
 * @interface MultipleArticlesResponse
 */
export interface MultipleArticlesResponse {
  /**
   * @type {Array<Article>}
   * @memberof MultipleArticlesResponse
   */
  articles: Array<Article>
  /**
   * @type {number}
   * @memberof MultipleArticlesResponse
   */
  articlesCount: number
}
