// tslint:disable
/**
 * Conduit API
 * Conduit API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface NewUser
 */
export interface NewUser {
  /**
   * @type {string}
   * @memberof NewUser
   */
  username: string
  /**
   * @type {string}
   * @memberof NewUser
   */
  email: string
  /**
   * @type {string}
   * @memberof NewUser
   */
  password: string
}
