// tslint:disable
/**
 * Conduit API
 * Conduit API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Profile } from './'

/**
 * @export
 * @interface ProfileResponse
 */
export interface ProfileResponse {
  /**
   * @type {Profile}
   * @memberof ProfileResponse
   */
  profile: Profile
}
