// tslint:disable
/**
 * Conduit API
 * Conduit API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Profile
 */
export interface Profile {
  /**
   * @type {string}
   * @memberof Profile
   */
  username: string
  /**
   * @type {string}
   * @memberof Profile
   */
  bio: string
  /**
   * @type {string}
   * @memberof Profile
   */
  image: string
  /**
   * @type {boolean}
   * @memberof Profile
   */
  following: boolean
}
