// tslint:disable
/**
 * Conduit API
 * Conduit API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UpdateUser
 */
export interface UpdateUser {
  /**
   * @type {string}
   * @memberof UpdateUser
   */
  email?: string
  /**
   * @type {string}
   * @memberof UpdateUser
   */
  password?: string
  /**
   * @type {string}
   * @memberof UpdateUser
   */
  username?: string
  /**
   * @type {string}
   * @memberof UpdateUser
   */
  bio?: string
  /**
   * @type {string}
   * @memberof UpdateUser
   */
  image?: string
}
