// tslint:disable
/**
 * Conduit API
 * Conduit API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface User
 */
export interface User {
  /**
   * @type {string}
   * @memberof User
   */
  email: string
  /**
   * @type {string}
   * @memberof User
   */
  token: string
  /**
   * @type {string}
   * @memberof User
   */
  username: string
  /**
   * @type {string}
   * @memberof User
   */
  bio: string
  /**
   * @type {string}
   * @memberof User
   */
  image: string
}
