// tslint:disable
/**
 * Conduit API
 * Conduit API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs'
import {
  BaseAPI,
  HttpHeaders,
  throwIfNullOrUndefined,
  encodeURI,
  OperationOpts,
  RawAjaxResponse,
} from '../runtime'
import { GenericErrorModel, SingleArticleResponse } from '../models'

export interface CreateArticleFavoriteRequest {
  slug: string
}

export interface DeleteArticleFavoriteRequest {
  slug: string
}

/**
 * no description
 */
export class FavoritesApi extends BaseAPI {
  /**
   * Favorite an article. Auth is required
   * Favorite an article
   */
  createArticleFavorite({
    slug,
  }: CreateArticleFavoriteRequest): Observable<SingleArticleResponse>
  createArticleFavorite(
    { slug }: CreateArticleFavoriteRequest,
    opts?: OperationOpts
  ): Observable<RawAjaxResponse<SingleArticleResponse>>
  createArticleFavorite(
    { slug }: CreateArticleFavoriteRequest,
    opts?: OperationOpts
  ): Observable<
    SingleArticleResponse | RawAjaxResponse<SingleArticleResponse>
  > {
    throwIfNullOrUndefined(slug, 'slug', 'createArticleFavorite')

    const headers: HttpHeaders = {
      ...(this.configuration.apiKey && {
        Authorization: this.configuration.apiKey('Authorization'),
      }), // Token authentication
    }

    return this.request<SingleArticleResponse>(
      {
        url: '/articles/{slug}/favorite'.replace('{slug}', encodeURI(slug)),
        method: 'POST',
        headers,
      },
      opts?.responseOpts
    )
  }

  /**
   * Unfavorite an article. Auth is required
   * Unfavorite an article
   */
  deleteArticleFavorite({
    slug,
  }: DeleteArticleFavoriteRequest): Observable<SingleArticleResponse>
  deleteArticleFavorite(
    { slug }: DeleteArticleFavoriteRequest,
    opts?: OperationOpts
  ): Observable<RawAjaxResponse<SingleArticleResponse>>
  deleteArticleFavorite(
    { slug }: DeleteArticleFavoriteRequest,
    opts?: OperationOpts
  ): Observable<
    SingleArticleResponse | RawAjaxResponse<SingleArticleResponse>
  > {
    throwIfNullOrUndefined(slug, 'slug', 'deleteArticleFavorite')

    const headers: HttpHeaders = {
      ...(this.configuration.apiKey && {
        Authorization: this.configuration.apiKey('Authorization'),
      }), // Token authentication
    }

    return this.request<SingleArticleResponse>(
      {
        url: '/articles/{slug}/favorite'.replace('{slug}', encodeURI(slug)),
        method: 'DELETE',
        headers,
      },
      opts?.responseOpts
    )
  }
}
